const KEY="habitflow.v1";let state=JSON.parse(localStorage.getItem(KEY)||"null")||{habits:[{id:crypto.randomUUID(),name:"Drink 2L of water",category:"Health",color:"#7c3aed",history:{}},{id:crypto.randomUUID(),name:"Read for 20 minutes",category:"Mind",color:"#2563eb",history:{}},{id:crypto.randomUUID(),name:"Move for 30 minutes",category:"Fitness",color:"#059669",history:{}}],theme:"auto"};let filter="all";
const $=s=>document.querySelector(s), today=()=>new Date().toISOString().slice(0,10), save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function formatDate(){return new Intl.DateTimeFormat(undefined,{weekday:"long",month:"long",day:"numeric"}).format(new Date())}
function isDone(h,d=today()){return !!h.history[d]}
function toggle(h){const d=today();h.history[d]=!h.history[d];if(!h.history[d])delete h.history[d];save();render()}
function streak(h){let n=0,d=new Date();while(isDone(h,d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
function best(h){const days=Object.keys(h.history).filter(k=>h.history[k]).sort();let max=0,cur=0,prev=null;for(const x of days){if(prev){const a=new Date(prev),b=new Date(x);if((b-a)/864e5!==1)cur=0}cur++;max=Math.max(max,cur);prev=x}return max}
function stats(){const habits=state.habits,done=habits.filter(h=>isDone(h)).length,total=habits.length;const all=habits.reduce((a,h)=>a+Object.values(h.history).filter(Boolean).length,0);const possible=habits.reduce((a,h)=>a+Object.keys(h.history).length,0);$("#todayProgress").style.width=(total?done/total*100:0)+"%";$("#todayProgressText").textContent=total?done+" of "+total+" complete":"0 of 0 complete";$("#streakStat").textContent=habits.length?Math.max(...habits.map(streak)):0;$("#bestStat").textContent=habits.length?Math.max(...habits.map(best)):0;$("#completionStat").textContent=(possible?Math.round(all/possible*100):0)+"%";$("#habitCountStat").textContent=total}
function render(){const list=$("#habitList"),empty=$("#emptyState");let hs=state.habits.filter(h=>filter==="all"||filter==="active"&&!isDone(h)||filter==="done"&&isDone(h));list.innerHTML=hs.map(h=>`<article class="habit ${isDone(h)?"done":""}"><button class="check" data-toggle="${h.id}" aria-label="Mark ${h.name} complete">${isDone(h)?"✓":""}</button><div><div class="habit-name">${esc(h.name)}</div><div class="habit-meta">${streak(h)} day streak • ${best(h)} best</div></div><span class="category" style="color:${h.color};background:${h.color}18">${esc(h.category)}</span><button class="menu" data-delete="${h.id}" aria-label="Delete ${h.name}">⋯</button></article>`).join("");empty.classList.toggle("hidden",state.habits.length>0);list.classList.toggle("hidden",!hs.length);stats();insight()}
function insight(){const complete=state.habits.filter(isDone).length;$("#insightTitle").textContent=complete===state.habits.length&&state.habits.length?"You showed up today.":"Consistency beats intensity.";$("#insightText").textContent=complete===state.habits.length&&state.habits.length?"Every habit is complete. Protect this momentum tomorrow.":"Complete one small action today. Momentum grows from repetition."}
function esc(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function openDialog(){$("#habitName").value="";$("#habitDialog").showModal();setTimeout(()=>$("#habitName").focus(),50)}
$("#todayDate").textContent=formatDate();$("#todayLabel").textContent="Today";$("#addBtn").onclick=openDialog;$("#emptyAddBtn").onclick=openDialog;$("#closeDialog").onclick=()=>$("#habitDialog").close();$("#cancelBtn").onclick=()=>$("#habitDialog").close();
$("#habitForm").onsubmit=e=>{e.preventDefault();const h={id:crypto.randomUUID(),name:$("#habitName").value.trim(),category:$("#habitCategory").value,color:$("#habitColor").value,history:{}};if(!h.name)return;state.habits.push(h);save();$("#habitDialog").close();render()};
$("#habitList").onclick=e=>{const t=e.target.closest("[data-toggle]"),d=e.target.closest("[data-delete]");if(t){const h=state.habits.find(x=>x.id===t.dataset.toggle);toggle(h)}if(d){const h=state.habits.find(x=>x.id===d.dataset.delete);if(confirm(`Delete "${h.name}"?`)){state.habits=state.habits.filter(x=>x.id!==h.id);save();render()}}};
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;render()});
$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");document.body.classList.toggle("light");state.theme=document.body.classList.contains("dark")?"dark":"light";save()};if(state.theme==="dark")document.body.classList.add("dark");if(state.theme==="light")document.body.classList.add("light");render();